import { Weapon } from '@/types/app.d';

interface WeaponList {
  [x:string]: Array<Weapon>
}

const coreWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      description: '',
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    description: '',
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    description: '',
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    description: '',
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    description: '',
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    description: '',
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    description: '',
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    description: '',
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    description: '',
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    description: '',
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    description: '',
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    description: '',
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    description: '',
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    description: '',
  }],
};

const kuluYaKuExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      description: '',
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    description: '',
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    description: '',
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    description: '',
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    description: '',
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    description: '',
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    description: '',
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    description: '',
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    description: '',
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    description: '',
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    description: '',
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    description: '',
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    description: '',
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    description: '',
  }],
};

const kusharadaoraExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      description: '',
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    description: '',
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    description: '',
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    description: '',
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    description: '',
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    description: '',
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    description: '',
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    description: '',
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    description: '',
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    description: '',
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    description: '',
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    description: '',
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    description: '',
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    description: '',
  }],
};

const teostraExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      description: '',
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    description: '',
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    description: '',
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    description: '',
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    description: '',
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    description: '',
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    description: '',
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    description: '',
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    description: '',
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    description: '',
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    description: '',
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    description: '',
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    description: '',
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    description: '',
  }],
};

const nergiganteExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      description: '',
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    description: '',
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    description: '',
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    description: '',
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    description: '',
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    description: '',
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    description: '',
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    description: '',
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    description: '',
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    description: '',
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    description: '',
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    description: '',
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    description: '',
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    description: '',
  }],
};

export {
  coreWeaponList,
  kuluYaKuExpansionWeaponList,
  kusharadaoraExpansionWeaponList,
  teostraExpansionWeaponList,
  nergiganteExpansionWeaponList,
};
