import { Weapon } from '@/types/app.d';

// Rarity:
// 1 : Grey
// 2 : Yellow
// 3 : Green
// 4 : Purple
// 5 : Orange

interface WeaponList {
  [x:string]: Array<Weapon>
}

const coreWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [{
    name: 'test',
    weaponType: 'Bow',
    abbreviation: 'bow',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  },
  ],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

const kuluYaKuExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

const kusharadaoraExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

const teostraExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

const nergiganteExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [{
    name: '',
    weaponType: 'Long Sword',
    abbreviation: 'ls',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

const hunterArsenalExpansionWeaponList:WeaponList = {
  bow: [
    {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    }, {
      name: '',
      weaponType: 'Bow',
      abbreviation: 'bow',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
      },
    },
  ],
  charge_blade: [{
    name: '',
    weaponType: 'Charge Blade',
    abbreviation: 'charge_blade',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ds: [{
    name: '',
    weaponType: 'Dual Blades',
    abbreviation: 'ds',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gs: [{
    name: '',
    weaponType: 'Great Sword',
    abbreviation: 'gs',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  gunlance: [{
    name: '',
    weaponType: 'Gunlance',
    abbreviation: 'gunlance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hammer: [{
    name: '',
    weaponType: 'Hammer',
    abbreviation: 'hammer',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hbg: [{
    name: '',
    weaponType: 'Heavy Bowgun',
    abbreviation: 'hbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  hh: [{
    name: '',
    weaponType: 'Hunting Horn',
    abbreviation: 'hh',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  insect_glaive: [{
    name: '',
    weaponType: 'Insect Glaive',
    abbreviation: 'insect_glaive',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lance: [{
    name: '',
    weaponType: 'Lance',
    abbreviation: 'lance',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  lbg: [{
    name: '',
    weaponType: 'Light Bowgun',
    abbreviation: 'lbg',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  ls: [
    {
      name: 'Iron Katana',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 9,
        2: 3,
        3: 0,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Bone Shotel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 1,
      deck: {
        remove: [],
        add: [],
      },
      attackCards: {
        1: 6,
        2: 4,
        3: 0,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Iron Grace',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 2,
      deck: {
        remove: ['2 Spirit Thrust'],
        add: ['2 Enhanced Thrust'],
      },
      attackCards: {
        1: 7,
        2: 5,
        3: 0,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Hard Bone Shotel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 2,
      deck: {
        remove: ['2 Foresight Slash'],
        add: ['2 Enhanced Foresight Slash'],
      },
      attackCards: {
        1: 4,
        2: 5,
        3: 1,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Iron Gospel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Spirit Thrust'],
        add: ['2 Enhanced Spirit Thrust', '2 Enhanced Overhead Slash'],
      },
      attackCards: {
        1: 5,
        2: 5,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Bone Reaper',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Foresight Slash', '3 Thrust'],
        add: ['2 Enhanced Foresight Slash', '3 Enhanced Thrust'],
      },
      attackCards: {
        1: 3,
        2: 5,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Pulsar Shotel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Fade Slash'],
        add: ['2 Thunder Fade Slash'],
      },
      attackCards: {
        1: 1,
        2: 7,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Blazing Shotel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Ready stance'],
        add: ['2 poised Stance'],
      },
      attackCards: {
        1: 1,
        2: 9,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Wyvern Blade "Fall"',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Rising Slash'],
        add: ['2 Blazing Rising Slash'],
      },
      attackCards: {
        1: 2,
        2: 8,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Jyura Shotel',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 3,
      deck: {
        remove: ['2 Helm Breaker'],
        add: ['2 Mud Helm Breaker'],
      },
      attackCards: {
        1: 2,
        2: 6,
        3: 2,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Kadachi Fang',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 4,
      deck: {
        remove: ['2 Rising Slash', '2 Fade Slash'],
        add: ['2 Shocking Rising Slash', '2 Thunder Fade Slash'],
      },
      attackCards: {
        1: 1,
        2: 8,
        3: 3,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Anja Scimitar',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 4,
      deck: {
        remove: ['2 Helm Breaker', '2 Ready Stance'],
        add: ['2 Flaming Helm Breaker', '2 Poised Stance'],
      },
      attackCards: {
        1: 1,
        2: 9,
        3: 4,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Wyvenr Blade "Blood',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 4,
      deck: {
        remove: ['2 Rising Slash', '2 Spirit Helm Breaker'],
        add: ['2 Blazing Rising Slash', '2 Blazing Spirit Helm Breaker'],
      },
      attackCards: {
        1: 2,
        2: 8,
        3: 4,
        4: 0,
        5: 0,
      },
    }, {
      name: 'Dipterus',
      weaponType: 'Long Sword',
      abbreviation: 'ls',
      rarity: 4,
      deck: {
        remove: ['2 Spirit Thrust', '2 Helm Breaker'],
        add: ['2 Water Spirit Thrust', '2 Mud Helm Breaker'],
      },
      attackCards: {
        1: 2,
        2: 7,
        3: 3,
        4: 0,
        5: 0,
      },
    },
  ],
  sns: [{
    name: '',
    weaponType: 'Sword and Shield',
    abbreviation: 'sns',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
  switch_axe: [{
    name: '',
    weaponType: 'Switch Axe',
    abbreviation: 'switch_axe',
    rarity: 1,
    deck: {
      remove: [],
      add: [],
    },
    attackCards: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
    },
  }],
};

export {
  coreWeaponList,
  kuluYaKuExpansionWeaponList,
  kusharadaoraExpansionWeaponList,
  teostraExpansionWeaponList,
  nergiganteExpansionWeaponList,
  hunterArsenalExpansionWeaponList,
};
